### ISSUE TITLE
PyOtherSide fails to build with Python 3.9

### ISSUE THREAD

**Issue by M4rtinK** [thp/pyotherside#111]
So Fedora is yet again getting ready to include the latest Python version, which yet again managed to break the PyOtherSide package build. ;-)

This time it looks like the build was successful, but one of the tests fails:

```
Executing(%check): /bin/sh -e /var/tmp/rpm-tmp.A3Csrv
+ umask 022
+ cd /builddir/build/BUILD
+ cd pyotherside-1.5.8
+ xvfb-run ./tests/tests
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-mockbuild'
********* Start testing of TestPyOtherSide *********
Config: Using QtTest library 5.13.2, Qt 5.13.2 (x86_64-little_endian-lp64
shared (dynamic) release build; by GCC 9.2.1 20190827 (Red Hat 9.2.1-1))
PASS   : TestPyOtherSide::initTestCase()
PASS   : TestPyOtherSide::testEvaluate()
PASS   : TestPyOtherSide::testQVariantConverter()

=== Received signal at function time: 0ms, total time: 23ms, dumping stack ===
=== End of stack trace ===
QFATAL : TestPyOtherSide::testPyObjectConverter() Received signal 11
         Function time: 0ms Total time: 23ms
FAIL!  : TestPyOtherSide::testPyObjectConverter() Received a fatal error.
   Loc: [Unknown file(0)]
Totals: 3 passed, 1 failed, 0 skipped, 0 blacklisted, 25ms
********* Finished testing of TestPyOtherSide *********
/usr/bin/xvfb-run: line 181:   548 Aborted                 (core dumped)
DISPLAY=:$SERVERNUM XAUTHORITY=$AUTHFILE "$@" 2>&1
error: Bad exit status from /var/tmp/rpm-tmp.A3Csrv (%check)
```

I guess this is the test that fails:

https://github.com/thp/pyotherside/blob/c67604ba4b0506f0082c6407cbe1d8f14bbe2c93/tests/tests.cpp#L253

Maybe [some C level Python API changes in 3.9](https://docs.python.org/3.9/whatsnew/3.9.html#build-and-c-api-changes) ?

More data & detailed logs from the build failure can be seen in the Fedora bug:
https://bugzilla.redhat.com/show_bug.cgi?id=1791966

Thanks in advance & let me know if there is something I can do further help you track this down. :)

**Comment by thp** [comment]
Also tagged version 1.5.9 with the fix for your convenience. Thanks for the bug report!

**Comment by M4rtinK** [comment]
Wow, that was fast! :) I've built 1.5.9 for Fedora, so it should be ready for when Fedora switches to 3.9. :)
