### ISSUE TITLE
Module not detected, assertion `pyotherside_mod' failed

### ISSUE THREAD

**Issue by kuba-orlik** [thp/pyotherside#120]
I'm trying to run PyOtherSide in a QT5 application in Manjaro GNU/Linux. QML can't find the pyotherside module even after I installed it from the community package. The files are all there:

```
$ find /usr/lib/qt/qml/io/thp                                                                                                                              
/usr/lib/qt/qml/io/thp
/usr/lib/qt/qml/io/thp/pyotherside
/usr/lib/qt/qml/io/thp/pyotherside/pyotherside.qmltypes
/usr/lib/qt/qml/io/thp/pyotherside/libpyothersideplugin.so
/usr/lib/qt/qml/io/thp/pyotherside/qmldir
```

But QML crashes and complains:

```
module "io.thp.pyotherside" is not installed
```

I've tried copying the `/usr/lib/qt/qml/io` dir to a directory within my project's root and pointed the `QML2_IMPORT_PATH` env variable at it, but then it gives me:

```
python3: qpython_priv.cpp:548: QPythonPriv::QPythonPriv(): Assertion `pyotherside_mod' failed.
```

**Comment by thp** [comment]
Yes, PyOtherSide is an alternative to PySide.
