### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by Yousjjw** [thp/pyotherside#127]
qpython_priv.cpp:526:35: error: ‘nullptr’ was not declared in this scope
     argv[0] = Py_DecodeLocale("", nullptr);
                                   ^
qpython_priv.cpp:526:42: error: ‘Py_DecodeLocale’ was not declared in this scope
     argv[0] = Py_DecodeLocale("", nullptr);

------------------------------------------------------------------------------------------
Python 3.4.2  
QMake version 3.0
Using Qt version 5.4.1 in /Qt5.4.1/5.4/gcc/lib

what's up ?

**Comment by thp** [comment]
Seems like your compiler is too old or the wrong C++ version is selected.
Please post more info about your build environment, including qmake logs
and full verbose make logs.

Yousjjw ***@***.***> schrieb am Di. 14. März 2023 um 14:41:

**Comment by Yousjjw** [comment]
thanks very much . 

------------------------------------------------------------------
additonal info 

root@debian [/home/janms/tools]  # g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/i586-linux-gnu/4.9/lto-wrapper
Target: i586-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 4.9.2-10' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-i386/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-i386 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-i386 --with-arch-directory=i386 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-targets=all --enable-multiarch --with-arch-32=i586 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=i586-linux-gnu --host=i586-linux-gnu --target=i586-linux-gnu
Thread model: posix
gcc version 4.9.2 (Debian 4.9.2-10) 
----------------------------------------------------------------------

# make
cd src/ && ( test -e Makefile || /Qt5.4.1/5.4/gcc/bin/qmake /home/janms/tools/pyotherside-1.6.0/src/src.pro PYTHON_CONFIG=python3.9-config -o Makefile ) && make -f Makefile 
make[1]: Entering directory '/home/janms/tools/pyotherside-1.6.0/src'
g++ -c -pipe -I/usr/include/python3.4m -I/usr/include/python3.4m -O2 -D_REENTRANT -Wall -W -fPIC -DPYOTHERSIDE_VERSION=\"1.6.0\" -DHAVE_DLADDR -DQT_NO_DEBUG -DQT_PLUGIN -DQT_QUICK_LIB -DQT_SVG_LIB -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I. -I/Qt5.4.1/5.4/gcc/include -I/Qt5.4.1/5.4/gcc/include/QtQuick -I/Qt5.4.1/5.4/gcc/include/QtSvg -I/Qt5.4.1/5.4/gcc/include/QtOpenGL -I/Qt5.4.1/5.4/gcc/include/QtWidgets -I/Qt5.4.1/5.4/gcc/include/QtGui -I/Qt5.4.1/5.4/gcc/include/QtQml -I/Qt5.4.1/5.4/gcc/include/QtNetwork -I/Qt5.4.1/5.4/gcc/include/QtCore -I. -I/Qt5.4.1/5.4/gcc/mkspecs/linux-g++ -o pyotherside_plugin.o pyotherside_plugin.cpp
pyotherside_plugin.cpp:46:78: warning: unused parameter ‘uri’ [-Wunused-parameter]
 PyOtherSideExtensionPlugin::initializeEngine(QQmlEngine *engine, const char *uri)
                                                                              ^
g++ -c -pipe -I/usr/include/python3.4m -I/usr/include/python3.4m -O2 -D_REENTRANT -Wall -W -fPIC -DPYOTHERSIDE_VERSION=\"1.6.0\" -DHAVE_DLADDR -DQT_NO_DEBUG -DQT_PLUGIN -DQT_QUICK_LIB -DQT_SVG_LIB -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I. -I/Qt5.4.1/5.4/gcc/include -I/Qt5.4.1/5.4/gcc/include/QtQuick -I/Qt5.4.1/5.4/gcc/include/QtSvg -I/Qt5.4.1/5.4/gcc/include/QtOpenGL -I/Qt5.4.1/5.4/gcc/include/QtWidgets -I/Qt5.4.1/5.4/gcc/include/QtGui -I/Qt5.4.1/5.4/gcc/include/QtQml -I/Qt5.4.1/5.4/gcc/include/QtNetwork -I/Qt5.4.1/5.4/gcc/include/QtCore -I. -I/Qt5.4.1/5.4/gcc/mkspecs/linux-g++ -o qpython_imageprovider.o qpython_imageprovider.cpp
qpython_imageprovider.cpp: In function ‘void cleanup_python_qimage(void*)’:
qpython_imageprovider.cpp:41:18: warning: unused variable ‘priv’ [-Wunused-variable]
     QPythonPriv *priv = QPythonPriv::instance();
                  ^
g++ -c -pipe -I/usr/include/python3.4m -I/usr/include/python3.4m -O2 -D_REENTRANT -Wall -W -fPIC -DPYOTHERSIDE_VERSION=\"1.6.0\" -DHAVE_DLADDR -DQT_NO_DEBUG -DQT_PLUGIN -DQT_QUICK_LIB -DQT_SVG_LIB -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I. -I/Qt5.4.1/5.4/gcc/include -I/Qt5.4.1/5.4/gcc/include/QtQuick -I/Qt5.4.1/5.4/gcc/include/QtSvg -I/Qt5.4.1/5.4/gcc/include/QtOpenGL -I/Qt5.4.1/5.4/gcc/include/QtWidgets -I/Qt5.4.1/5.4/gcc/include/QtGui -I/Qt5.4.1/5.4/gcc/include/QtQml -I/Qt5.4.1/5.4/gcc/include/QtNetwork -I/Qt5.4.1/5.4/gcc/include/QtCore -I. -I/Qt5.4.1/5.4/gcc/mkspecs/linux-g++ -o pyglarea.o pyglarea.cpp
g++ -c -pipe -I/usr/include/python3.4m -I/usr/include/python3.4m -O2 -D_REENTRANT -Wall -W -fPIC -DPYOTHERSIDE_VERSION=\"1.6.0\" -DHAVE_DLADDR -DQT_NO_DEBUG -DQT_PLUGIN -DQT_QUICK_LIB -DQT_SVG_LIB -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I. -I/Qt5.4.1/5.4/gcc/include -I/Qt5.4.1/5.4/gcc/include/QtQuick -I/Qt5.4.1/5.4/gcc/include/QtSvg -I/Qt5.4.1/5.4/gcc/include/QtOpenGL -I/Qt5.4.1/5.4/gcc/include/QtWidgets -I/Qt5.4.1/5.4/gcc/include/QtGui -I/Qt5.4.1/5.4/gcc/include/QtQml -I/Qt5.4.1/5.4/gcc/include/QtNetwork -I/Qt5.4.1/5.4/gcc/include/QtCore -I. -I/Qt5.4.1/5.4/gcc/mkspecs/linux-g++ -o pyglrenderer.o pyglrenderer.cpp
g++ -c -pipe -I/usr/include/python3.4m -I/usr/include/python3.4m -O2 -D_REENTRANT -Wall -W -fPIC -DPYOTHERSIDE_VERSION=\"1.6.0\" -DHAVE_DLADDR -DQT_NO_DEBUG -DQT_PLUGIN -DQT_QUICK_LIB -DQT_SVG_LIB -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I. -I/Qt5.4.1/5.4/gcc/include -I/Qt5.4.1/5.4/gcc/include/QtQuick -I/Qt5.4.1/5.4/gcc/include/QtSvg -I/Qt5.4.1/5.4/gcc/include/QtOpenGL -I/Qt5.4.1/5.4/gcc/include/QtWidgets -I/Qt5.4.1/5.4/gcc/include/QtGui -I/Qt5.4.1/5.4/gcc/include/QtQml -I/Qt5.4.1/5.4/gcc/include/QtNetwork -I/Qt5.4.1/5.4/gcc/include/QtCore -I. -I/Qt5.4.1/5.4/gcc/mkspecs/linux-g++ -o pyfbo.o pyfbo.cpp
g++ -c -pipe -I/usr/include/python3.4m -I/usr/include/python3.4m -O2 -D_REENTRANT -Wall -W -fPIC -DPYOTHERSIDE_VERSION=\"1.6.0\" -DHAVE_DLADDR -DQT_NO_DEBUG -DQT_PLUGIN -DQT_QUICK_LIB -DQT_SVG_LIB -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I. -I/Qt5.4.1/5.4/gcc/include -I/Qt5.4.1/5.4/gcc/include/QtQuick -I/Qt5.4.1/5.4/gcc/include/QtSvg -I/Qt5.4.1/5.4/gcc/include/QtOpenGL -I/Qt5.4.1/5.4/gcc/include/QtWidgets -I/Qt5.4.1/5.4/gcc/include/QtGui -I/Qt5.4.1/5.4/gcc/include/QtQml -I/Qt5.4.1/5.4/gcc/include/QtNetwork -I/Qt5.4.1/5.4/gcc/include/QtCore -I. -I/Qt5.4.1/5.4/gcc/mkspecs/linux-g++ -o pythonlib_loader.o pythonlib_loader.cpp
g++ -c -pipe -I/usr/include/python3.4m -I/usr/include/python3.4m -O2 -D_REENTRANT -Wall -W -fPIC -DPYOTHERSIDE_VERSION=\"1.6.0\" -DHAVE_DLADDR -DQT_NO_DEBUG -DQT_PLUGIN -DQT_QUICK_LIB -DQT_SVG_LIB -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I. -I/Qt5.4.1/5.4/gcc/include -I/Qt5.4.1/5.4/gcc/include/QtQuick -I/Qt5.4.1/5.4/gcc/include/QtSvg -I/Qt5.4.1/5.4/gcc/include/QtOpenGL -I/Qt5.4.1/5.4/gcc/include/QtWidgets -I/Qt5.4.1/5.4/gcc/include/QtGui -I/Qt5.4.1/5.4/gcc/include/QtQml -I/Qt5.4.1/5.4/gcc/include/QtNetwork -I/Qt5.4.1/5.4/gcc/include/QtCore -I. -I/Qt5.4.1/5.4/gcc/mkspecs/linux-g++ -o qpython.o qpython.cpp
g++ -c -pipe -I/usr/include/python3.4m -I/usr/include/python3.4m -O2 -D_REENTRANT -Wall -W -fPIC -DPYOTHERSIDE_VERSION=\"1.6.0\" -DHAVE_DLADDR -DQT_NO_DEBUG -DQT_PLUGIN -DQT_QUICK_LIB -DQT_SVG_LIB -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I. -I/Qt5.4.1/5.4/gcc/include -I/Qt5.4.1/5.4/gcc/include/QtQuick -I/Qt5.4.1/5.4/gcc/include/QtSvg -I/Qt5.4.1/5.4/gcc/include/QtOpenGL -I/Qt5.4.1/5.4/gcc/include/QtWidgets -I/Qt5.4.1/5.4/gcc/include/QtGui -I/Qt5.4.1/5.4/gcc/include/QtQml -I/Qt5.4.1/5.4/gcc/include/QtNetwork -I/Qt5.4.1/5.4/gcc/include/QtCore -I. -I/Qt5.4.1/5.4/gcc/mkspecs/linux-g++ -o qpython_worker.o qpython_worker.cpp
g++ -c -pipe -I/usr/include/python3.4m -I/usr/include/python3.4m -O2 -D_REENTRANT -Wall -W -fPIC -DPYOTHERSIDE_VERSION=\"1.6.0\" -DHAVE_DLADDR -DQT_NO_DEBUG -DQT_PLUGIN -DQT_QUICK_LIB -DQT_SVG_LIB -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I. -I/Qt5.4.1/5.4/gcc/include -I/Qt5.4.1/5.4/gcc/include/QtQuick -I/Qt5.4.1/5.4/gcc/include/QtSvg -I/Qt5.4.1/5.4/gcc/include/QtOpenGL -I/Qt5.4.1/5.4/gcc/include/QtWidgets -I/Qt5.4.1/5.4/gcc/include/QtGui -I/Qt5.4.1/5.4/gcc/include/QtQml -I/Qt5.4.1/5.4/gcc/include/QtNetwork -I/Qt5.4.1/5.4/gcc/include/QtCore -I. -I/Qt5.4.1/5.4/gcc/mkspecs/linux-g++ -o qpython_priv.o qpython_priv.cpp
qpython_priv.cpp:526:5: warning: identifier ‘nullptr’ is a keyword in C++11 [-Wc++0x-compat]
     argv[0] = Py_DecodeLocale("", nullptr);
     ^
qpython_priv.cpp:77:1: warning: missing initializer for member ‘_typeobject::tp_traverse’ [-Wmissing-field-initializers]
 };
 ^
qpython_priv.cpp:77:1: warning: missing initializer for member ‘_typeobject::tp_clear’ [-Wmissing-field-initializers]
qpython_priv.cpp:77:1: warning: missing initializer for member ‘_typeobject::tp_richcompare’ [-Wmissing-field-initializers]
qpython_priv.cpp:77:1: warning: missing initializer for member ‘_typeobject::tp_weaklistoffset’ [-Wmissing-field-initializers]
qpython_priv.cpp:77:1: warning: missing initializer for member ‘_typeobject::tp_iter’ [-Wmissing-field-initializers]
qpython_priv.cpp:77:1: warning: missing initializer for member ‘_typeobject::tp_iternext’ [-Wmissing-field-initializers]
qpython_priv.cpp:77:1: warning: missing initializer for member ‘_typeobject::tp_methods’ [-Wmissing-field-initializers]
qpython_priv.cpp:77:1: warning: missing initializer for member ‘_typeobject::tp_members’ [-Wmissing-field-initializers]
qpython_priv.cpp:77:1: warning: missing initializer for member ‘_typeobject::tp_getset’ [-Wmissing-field-initializers]
qpython_priv.cpp:77:1: warning: missing initializer for member ‘_typeobject::tp_base’ [-Wmissing-field-initializers]
qpython_priv.cpp:77:1: warning: missing initializer for member ‘_typeobject::tp_dict’ [-Wmissing-field-initializers]
qpython_priv.cpp:77:1: warning: missing initializer for member ‘_typeobject::tp_descr_get’ [-Wmissing-field-initializers]
qpython_priv.cpp:77:1: warning: missing initializer for member ‘_typeobject::tp_descr_set’ [-Wmissing-field-initializers]
qpython_priv.cpp:77:1: warning: missing initializer for member ‘_typeobject::tp_dictoffset’ [-Wmissing-field-initializers]
qpython_priv.cpp:77:1: warning: missing initializer for member ‘_typeobject::tp_init’ [-Wmissing-field-initializers]
qpython_priv.cpp:77:1: warning: missing initializer for member ‘_typeobject::tp_alloc’ [-Wmissing-field-initializers]
qpython_priv.cpp:77:1: warning: missing initializer for member ‘_typeobject::tp_new’ [-Wmissing-field-initializers]
qpython_priv.cpp:77:1: warning: missing initializer for member ‘_typeobject::tp_free’ [-Wmissing-field-initializers]
qpython_priv.cpp:77:1: warning: missing initializer for member ‘_typeobject::tp_is_gc’ [-Wmissing-field-initializers]
qpython_priv.cpp:77:1: warning: missing initializer for member ‘_typeobject::tp_bases’ [-Wmissing-field-initializers]
qpython_priv.cpp:77:1: warning: missing initializer for member ‘_typeobject::tp_mro’ [-Wmissing-field-initializers]
qpython_priv.cpp:77:1: warning: missing initializer for member ‘_typeobject::tp_cache’ [-Wmissing-field-initializers]
qpython_priv.cpp:77:1: warning: missing initializer for member ‘_typeobject::tp_subclasses’ [-Wmissing-field-initializers]
qpython_priv.cpp:77:1: warning: missing initializer for member ‘_typeobject::tp_weaklist’ [-Wmissing-field-initializers]
qpython_priv.cpp:77:1: warning: missing initializer for member ‘_typeobject::tp_del’ [-Wmissing-field-initializers]
qpython_priv.cpp:77:1: warning: missing initializer for member ‘_typeobject::tp_version_tag’ [-Wmissing-field-initializers]
qpython_priv.cpp:77:1: warning: missing initializer for member ‘_typeobject::tp_finalize’ [-Wmissing-field-initializers]
qpython_priv.cpp:101:1: warning: missing initializer for member ‘_typeobject::tp_traverse’ [-Wmissing-field-initializers]
 };
 ^
qpython_priv.cpp:101:1: warning: missing initializer for member ‘_typeobject::tp_clear’ [-Wmissing-field-initializers]
qpython_priv.cpp:101:1: warning: missing initializer for member ‘_typeobject::tp_richcompare’ [-Wmissing-field-initializers]
qpython_priv.cpp:101:1: warning: missing initializer for member ‘_typeobject::tp_weaklistoffset’ [-Wmissing-field-initializers]
qpython_priv.cpp:101:1: warning: missing initializer for member ‘_typeobject::tp_iter’ [-Wmissing-field-initializers]
qpython_priv.cpp:101:1: warning: missing initializer for member ‘_typeobject::tp_iternext’ [-Wmissing-field-initializers]
qpython_priv.cpp:101:1: warning: missing initializer for member ‘_typeobject::tp_methods’ [-Wmissing-field-initializers]
qpython_priv.cpp:101:1: warning: missing initializer for member ‘_typeobject::tp_members’ [-Wmissing-field-initializers]
qpython_priv.cpp:101:1: warning: missing initializer for member ‘_typeobject::tp_getset’ [-Wmissing-field-initializers]
qpython_priv.cpp:101:1: warning: missing initializer for member ‘_typeobject::tp_base’ [-Wmissing-field-initializers]
qpython_priv.cpp:101:1: warning: missing initializer for member ‘_typeobject::tp_dict’ [-Wmissing-field-initializers]
qpython_priv.cpp:101:1: warning: missing initializer for member ‘_typeobject::tp_descr_get’ [-Wmissing-field-initializers]
qpython_priv.cpp:101:1: warning: missing initializer for member ‘_typeobject::tp_descr_set’ [-Wmissing-field-initializers]
qpython_priv.cpp:101:1: warning: missing initializer for member ‘_typeobject::tp_dictoffset’ [-Wmissing-field-initializers]
qpython_priv.cpp:101:1: warning: missing initializer for member ‘_typeobject::tp_init’ [-Wmissing-field-initializers]
qpython_priv.cpp:101:1: warning: missing initializer for member ‘_typeobject::tp_alloc’ [-Wmissing-field-initializers]
qpython_priv.cpp:101:1: warning: missing initializer for member ‘_typeobject::tp_new’ [-Wmissing-field-initializers]
qpython_priv.cpp:101:1: warning: missing initializer for member ‘_typeobject::tp_free’ [-Wmissing-field-initializers]
qpython_priv.cpp:101:1: warning: missing initializer for member ‘_typeobject::tp_is_gc’ [-Wmissing-field-initializers]
qpython_priv.cpp:101:1: warning: missing initializer for member ‘_typeobject::tp_bases’ [-Wmissing-field-initializers]
qpython_priv.cpp:101:1: warning: missing initializer for member ‘_typeobject::tp_mro’ [-Wmissing-field-initializers]
qpython_priv.cpp:101:1: warning: missing initializer for member ‘_typeobject::tp_cache’ [-Wmissing-field-initializers]
qpython_priv.cpp:101:1: warning: missing initializer for member ‘_typeobject::tp_subclasses’ [-Wmissing-field-initializers]
qpython_priv.cpp:101:1: warning: missing initializer for member ‘_typeobject::tp_weaklist’ [-Wmissing-field-initializers]
qpython_priv.cpp:101:1: warning: missing initializer for member ‘_typeobject::tp_del’ [-Wmissing-field-initializers]
qpython_priv.cpp:101:1: warning: missing initializer for member ‘_typeobject::tp_version_tag’ [-Wmissing-field-initializers]
qpython_priv.cpp:101:1: warning: missing initializer for member ‘_typeobject::tp_finalize’ [-Wmissing-field-initializers]
qpython_priv.cpp:106:28: warning: unused parameter ‘self’ [-Wunused-parameter]
 pyotherside_send(PyObject *self, PyObject *args)
                            ^
qpython_priv.cpp:113:30: warning: unused parameter ‘self’ [-Wunused-parameter]
 pyotherside_atexit(PyObject *self, PyObject *o)
                              ^
qpython_priv.cpp:121:42: warning: unused parameter ‘self’ [-Wunused-parameter]
 pyotherside_set_image_provider(PyObject *self, PyObject *o)
                                          ^
qpython_priv.cpp:129:35: warning: unused parameter ‘self’ [-Wunused-parameter]
 pyotherside_qrc_is_file(PyObject *self, PyObject *filename)
                                   ^
qpython_priv.cpp:145:34: warning: unused parameter ‘self’ [-Wunused-parameter]
 pyotherside_qrc_is_dir(PyObject *self, PyObject *dirname)
                                  ^
qpython_priv.cpp:161:45: warning: unused parameter ‘self’ [-Wunused-parameter]
 pyotherside_qrc_get_file_contents(PyObject *self, PyObject *filename)
                                             ^
qpython_priv.cpp:180:36: warning: unused parameter ‘self’ [-Wunused-parameter]
 pyotherside_qrc_list_dir(PyObject *self, PyObject *dirname)
                                    ^
qpython_priv.cpp:454:1: warning: missing initializer for member ‘PyModuleDef::m_reload’ [-Wmissing-field-initializers]
 };
 ^
qpython_priv.cpp:454:1: warning: missing initializer for member ‘PyModuleDef::m_traverse’ [-Wmissing-field-initializers]
qpython_priv.cpp:454:1: warning: missing initializer for member ‘PyModuleDef::m_clear’ [-Wmissing-field-initializers]
qpython_priv.cpp:454:1: warning: missing initializer for member ‘PyModuleDef::m_free’ [-Wmissing-field-initializers]
qpython_priv.cpp: In constructor ‘QPythonPriv::QPythonPriv()’:
qpython_priv.cpp:526:35: error: ‘nullptr’ was not declared in this scope
     argv[0] = Py_DecodeLocale("", nullptr);
                                   ^
qpython_priv.cpp:526:42: error: ‘Py_DecodeLocale’ was not declared in this scope
     argv[0] = Py_DecodeLocale("", nullptr);
                                          ^
Makefile:2551: recipe for target 'qpython_priv.o' failed
make[1]: *** [qpython_priv.o] Error 1
make[1]: Leaving directory '/home/janms/tools/pyotherside-1.6.0/src'
Makefile:44: recipe for target 'sub-src-make_first' failed
make: *** [sub-src-make_first] Error 2

**Comment by thp** [comment]
GCC 4.9 is quite old and has been removed from Debian in 2016 (added in 2014):
https://tracker.debian.org/pkg/gcc-4.9

Please upgrade to a newer version. You can try specifying `CXX="g++ -std=c++11"` when configuring, but there are probably other issues, so please just upgrade to a newer version.

**Comment by Yousjjw** [comment]
ok, thx , I will have a try.
