### ISSUE TITLE
"Advanced" python module imports

### ISSUE THREAD

**Issue by mattaustin** [thp/pyotherside#15]
Low priority, but a 'nice to have' feature request:

1) Selecting specific module for import: ```from x.y.z import a, b, c```

2) Aliasing a module to an alternative name: ```from x.y.z import a as b```

Example: An application might have some specific code for use with pyotherside. It may make sense to call the module containing this code "pyotherside", however, this then might clash with the existing "pyotherside" module. Therefore when importing, it would have to be included with a different name.

```from myapp.ui import pyotherside as ui```

**Comment by thp** [comment]
The more I think about this, the more I think this is better solved by having a simple "main" script that gets imported from QML and the main script takes care of aliasing imports:

<b>main.py</b>
```
import pyotherside
from x.y.z import pyotherside as app

bar_func = app.bar_func
```

<b>main.qml</b>
```
...
Python {
   id: py
   Component.onCompleted: {
      importModule('main', function () {
         call('main.bar_func', [], function () { ... });
      });
   }
}
```

**Comment by mattaustin** [comment]
I think that's probably a completely reasonable approach - might be a good idea to include this suggestion in the docs somewhere too if that's the design decision.

**Comment by thp** [comment]
Ok, closing. Feel free to submit a pull request with doc updates.

**Comment by xealits** [comment]
Sorry for bringing up this old discussion,
but have you considered adding `from module import *`?

If you don't have it you have to repeat `main.` in your QML calls all the time. Well,  probably one can make a special function for the prefix. But it seems like a good thing to have in PyOtherSide by default, it goes well with the idea of `main` module.

**Comment by thp** [comment]
Python's PEP-8 suggests that wildcard imports (`from module import *`) are discouraged. We could probably add something like `importNames('main', ['foo', 'bar']);` that does the equivalent of `from main import foo, bar`? Anyway, you probably want to open a new issue for that if you want to see it implemented (or even better, implement it and make a pull request ;).
