### ISSUE TITLE
Documentation request: PyOtherSide on Android

### ISSUE THREAD

**Issue by mattaustin** [thp/pyotherside#16]
A low-priority documentation request.

I'm intrigued at the possibility for PyOtherSide on Android, as was hinted at in the [Qt Developer Days](http://thp.io/2013/qtdevdays/) presentation. I understand this would involve bundling Qt, Python, and PyOtherSide with my app, but I have no experience with Android and don't know where to begin. A tutorial or guide on how this might be possible would be very welcome.

**Comment by thp** [comment]
This is already done here: https://github.com/thp/pyotherside/commit/9d292e2f3a61ea661ed52084ab7abdc05acc774f

**Comment by mattaustin** [comment]
Thanks @thp and @M4rtinK ! I must admit that I've struggled a little to get a working PyOtherSide app - lots of segfaults when running on my Android device - but if I can determine what is causing this (and if it isn't my own fault) I'll open another issue.
