### ISSUE TITLE
Cannot run two functions concurrently.

### ISSUE THREAD

**Issue by Druage** [thp/pyotherside#18]
Do you have any plans on implementing multiprocesses or threading into pyotherside, without managing it myself? I do not mind doing it myself, I just think that it would clean up the code if you were able to set a flag in the Python {} component; or possibly adding something like: 

Python {
    //...
    importModule('scan_system', function() {})
    importModule('check_system', function() {
        multiprocessCall('check_system.check', [], function(result) {console.log(result)}, 
                                   'scan_system.scan, [], function(result) {console.log(result)} )
    })
}

**Comment by thp** [comment]
For now, I've mostly avoided adding multiprocessing/-threading API to PyOtherSide, as using QML WorkerScript and threads on the Python side works fine mostly. Keeping this open for a little longer, maybe we get some inspiration on how to do this in a nice way.
