### ISSUE TITLE
Statically linking Python and shipping with application

### ISSUE THREAD

**Issue by Druage** [thp/pyotherside#21]
I did not see any way to contact you on either this github page or on your developer guide, since don't want to flood your issues section with questions. Since you are here anways, is there a way to build pyotherside statically with python, for easy distribution? If not, how do you go about distributing python with an application, besides just providing the user with the standard python msi installer? Thanks.

**Comment by thp** [comment]
Documented here:

https://github.com/thp/pyotherside/commit/9d292e2f3a61ea661ed52084ab7abdc05acc774f
