### ISSUE TITLE
importModule runs forever

### ISSUE THREAD

**Issue by nadrimajstor** [thp/pyotherside#23]
```qml
import QtQuick 2.0
import io.thp.pyotherside 1.2

Rectangle {
    width: 300
    height: 300
    Python {
        Component.onCompleted: {
//            importModule('gi.repository.Gio', function(){
//                console.log('import completed')
//            })
            importModule_sync('gi.repository.Gio');
            call("gi.repository.Gio.Settings.new('org.gnome.Vino').keys", [], function(result){console.log(result)});
        }
        onError: console.log('Error: ' + traceback)
    }
}
```
Possibly an edge case with this particular library:
Synchronous call works just fine.
However its (commented out) counterpart runs forever and never reach the callback function. Closing qmlscene removes the visible window but the process is still live until manually killed.

**Comment by thp** [comment]
For me, this works fine with the latest version of PyOtherSide from Git. I've added a test case in 5b76536332f6b442f6e3d6310c72e7ab2c63451c that is basically your example, and for me, this shows the text properly.

**Comment by nadrimajstor** [comment]
I can confirm - latest pyotherside from Git works fine for me also. Thank you.
