### ISSUE TITLE
Cannot convert QVariant to QJSValue in example code

### ISSUE THREAD

**Issue by cochise** [thp/pyotherside#32]
Using Qt 5.4.0 and Python 3.4.2 on Archlinux I can't get values from python on QML, due casting error. The evaluate one line example runs without problems. 
The example (and also, there is a missing bracket on it) and the output:
```
Python {
    Component.onCompleted: {
        importModule('os', function() {
            call('os.getcwd', [], function (result) {
                console.log('Working directory: ' + result);
                call('os.chdir', ['/'], function (result) {
                    console.log('Working directory changed.');
                });});
            });
        });
    }
}

Cannot convert: QVariant(QJSValue, )
qml: Working directory: undefined
Cannot convert: QVariant(QJSValue, )
qml: Working directory changed.
```

**Comment by thp** [comment]
Is this a duplicate of https://github.com/thp/pyotherside/pull/29? If so, this has been fixed in Git, but not released yet - I should probably do another release soon ;)

**Comment by cochise** [comment]
Tanks. I will test the git today to see if this is the case.

**Comment by cochise** [comment]
Git works, so probably is a duplicate of #29. 
As the last released version is broken against last released version of Qt, maybe you should make a bugfix release. 

Thanks.
