### ISSUE TITLE
Ctrl+C stops working after loading a qml that inclues the Python element

### ISSUE THREAD

**Issue by 3v1n0** [thp/pyotherside#33]
Any simple example that uses pyotherside can't be closed by using Ctrl+C from the parent terminal.

**Comment by 3v1n0** [comment]
Thanks.

This works for all the standard examples you provided, but as soon as I do something like:
```python
from gi.repository import Gio
```
The fix doesn't work anymore... Not sure wether this is an issue related to that (I knew that also standard pygtk3 apps have this problem, but I don't recall a case related to Gio/GLib ones).

**Comment by thp** [comment]
Probably because this import does some special signal handing. Try this Python snippet after the import:

```
import signal
signal.signal(signal.SIGINT, signal.SIG_DFL)
```

**Comment by 3v1n0** [comment]
I already tried this before and it wasn't working for some reason, but now it seems to do the trick.
Thanks
