### ISSUE TITLE
Could you please evaluate the difficulty of porting pyotherside to Python 2.7?

### ISSUE THREAD

**Issue by Readon** [thp/pyotherside#35]
pyotherside is a great project that makes Python support QML for the latest Qt lib.
However, It only support Python 3 which limited it's usage, especially there are still a large amount of python library support only Python 2. And pypy, the jit version of Python, is based on version 2.7 too.

Is there large gap could stop pyotherside be ported to Python2.7?
If it is possible, maybe we could try to do something on this.

**Comment by thp** [comment]
Yes, it is possible to add Python 2 support to PyOtherSide. Do you want to do it yourself as a hobby project or do you need it in a commercial setting?

**Comment by Readon** [comment]
Just for fun, Python2 is still widly used in many project.
Maybe we will use it in future, when Python 2.7is supported.:).

**Comment by thp** [comment]
Closing for now, there are currently no plans to support Python 2.7 except if somebody wants to do it and maintain it (in that case, send a pull request).
