### ISSUE TITLE
Old pythonlib.zip not updated on package reinstall on Android

### ISSUE THREAD

**Issue by M4rtinK** [thp/pyotherside#41]
If a package is reinstalled on Android, local data is kept, including the cache folder and the pythonlib.zip file. As a result PyOtherSide keeps using the old zip file, even if it might have a newer one compiled in. This can cause issues as the old file might be missing some Python modules or worse - contains shared libraries compiled against a different Python version.

Reinstall happens when a user installs a package update (a package with higher Android version number) and can also be triggered manually:

  adb install -r <path to an apk>

A possible solution (until issue #30 hopefully makes extracting the zip file obsolete) could be to compile some sort build/pythonlib identificator (hash of the zip file, current epoch, etc.) into the PyOtherSide binary and use it as part of the filename when extracting the pythonlib.zip file: cache/pythonlib_<hash>.zip

On each startup PyOtherSide would check if cache/pythonlib_<hash>.zip exists, if it does not, it would first delete all old pythonlib files (cache/pythonlib_*.zip) and then would extract the zip from qrc and store it as cache/pythonlib_<hash>.zip.

**Comment by thp** [comment]
Yep, known issue. I'd like to focus on getting #30 fixed first instead of instroducing a workaround.

**Comment by M4rtinK** [comment]
OK, that sounds like a good idea. And I can work around it myself in modRana for the time being - I already have a version change detection, so I can use that to remove the pythonlib.zip file on package update. :)

**Comment by thp** [comment]
How did you implement the version change detection? If we can't get appending the .zip file to the .so to work, doing version change detection as you described might be a good fallback.

**Comment by M4rtinK** [comment]
Well, it is rather application specific and I'm not sure how much it might be directly applicable to PyOtherSide:
https://github.com/M4rtinK/modrana/blob/master/core/qrc.py#L91
ModRana stores its version in a text file called version.txt, so it checks the content of version.txt file on the local filesystem (if it exists) with the version.txt content in the qrc bundle. If it differs, all the unpacked data on the local filesystem (example tracklogs, default configuration files, etc.) is removed and replaced with newly exported data from the qrc bundle, including the new version.txt file.
When the content of "local" version.txt and version.txt in the bundle is the same (it does not check if it is more or less, just difference) nothing is done as the unpacked data corresponds to the data in the qrc bundle.

I'm afraid that the same version change check won't work for PyOtherSide as different applications might have different versioning methods and even the same PyOtherSide version can be used with different pythonlib.zip file. An even  a single Python 3 build  might be used to create multiple pythonlib.zip files (by removing modules, etc.).

What needs to be done is to check if the file on the local filesystem is the same as the one in the qrc bundle and replace it by the from the qrc if it differs. We can also more or less assume that PyOtherSide is the single owner of the file and no other software or users will be manipulating it. So we don't need to check the integrity of the file on each start and can assume that its checksum never changes and can thus be used as an unique "version number".

This is how I think it could be done:

* pythonlib_loader.qrc should have a second line with *<file>pythonlib.zip.md5</file>*
* if pythonlib.zip is present in the src directory, run a script (it should be possible[0][1]) that makes a md5 checksum of the *pythonlib.zip* file and stores it in the pythonlib.zip.md5 file in the *src* folder
* both *pythonlib.zip* and *pythonlib.zip.md5* get picked up by the qrc compiler and compiled into the qrc bundle in the libpyotherside.so binary
* then on startup *PythonLibLoader* will compare the content of *pythonlib.zip.md5* on local storage and on the qrc bundle
* if the content of the checksum files differ, it removes both *pythonlib.zip.md5* and *pythonlib.zip* and replaces them with the versions from the qrc bundle
* if the content is the same, nothing needs to be done as the *pythonlib.zip* in the local storage is the same as the one in the qrc bundle

[0] http://stackoverflow.com/questions/15766208/qt-run-a-script-before-make
[1] http://stackoverflow.com/questions/3612283/running-a-program-script-from-qmake

**Comment by thp** [comment]
Let's fix this in a application-specific way for now.
