### ISSUE TITLE
pyotherside does not import in Ubuntu 14.04 in a python file

### ISSUE THREAD

**Issue by JeffHoogland** [thp/pyotherside#43]
Apologies this is likely the wrong place to post this, but I do not see an IRC channel, forum, or mailing list listed for getting help with pyotherside. If there is one of the above please direct me there.

I am trying to work with pyotherside on Ubuntu 14.04 (version 1.2). When I add:

    import io.thp.pyotherside 1.2

To my qml file it imports successfully.

However when I add:

    import pyotherside

To a python file, it fails to import. Do I need to install something other than the pyotherside package on Ubuntu to access pyotherside from a python file?

**Comment by zyga** [comment]
I think the mistake you are making is that you are trying to import
pyotherside from a regular python module.

Py*other*side swaps that idea around. Use QML and javascript to load any
python module. That module (only when loaded from QML) can then see the
special pyotherside module.

Have a look at pyotherside examples for some ... well, examples!

Best regards
ZK

2015-04-07 22:05 GMT+02:00 Jeff Hoogland <notifications@github.com>:

**Comment by JeffHoogland** [comment]
Doesn't it go in both directions? Look at this example here -> http://pyotherside.readthedocs.org/en/latest/#handling-asynchronous-events-from-python-in-qml

Am I misunderstanding that example about sending data from python code back to QML?

**Comment by zyga** [comment]
It does but you cannot run any of those by executing python3 and importing
pyotherside.

2015-04-07 23:15 GMT+02:00 Jeff Hoogland <notifications@github.com>:

**Comment by JeffHoogland** [comment]
Ahh - so import pyotherside only works in a python file when that python file is called from QML?

**Comment by zyga** [comment]
Yes, exactly.

2015-04-07 23:31 GMT+02:00 Jeff Hoogland <notifications@github.com>:

**Comment by JeffHoogland** [comment]
Thank you.
