### ISSUE TITLE
ImportError: No module named 'commands'

### ISSUE THREAD

**Issue by 0312birdzhang** [thp/pyotherside#44]
I used io.thp.pyotherside 1.4,it seems not contains commands module.
On jolla,i use terminal,i can use <code>import commands</code>

**Comment by thp** [comment]
As documented in https://docs.python.org/2/library/commands.html:

<q>Deprecated since version 2.6: The commands module has been removed in Python 3. Use the subprocess module instead.</q>

PyOtherSide runs using Python 3, use subprocess instead:

https://docs.python.org/3/library/subprocess.html

**Comment by 0312birdzhang** [comment]
:sweat_smile: Thank you.
