### ISSUE TITLE
PyGLArea works with Window, but not ApplicationWindow

### ISSUE THREAD

**Issue by Moguri** [thp/pyotherside#47]
I've taken the pyglarea.qml demo and replaced the outer-most Item with Window from QtQuick.Window, and this appears to work as expected. If I instead use an ApplicationWindow from QtQuick.Controls, the PyGLArea does not show up. The other widgets show up, but on top of the grey background of the ApplicationWindow.

Is this a known limitation of PyGLArea? Is it possible to add support for using PyGLArea with an ApplicationWindow, or is there some restriction (e.g., from ApplicationWindow) that makes this difficult?

If this is a known limitation, it would be nice to have the docs mention the limitation.

**Comment by thp** [comment]
Can you post some [short, self-contained, correct example](http://sscce.org/) code that demonstrates the problem?

**Comment by Moguri** [comment]
I have reduced the pyglarea example code down to what I believe is the minimum needed to show what I am talking about.

QML:
```qml
import QtQuick 2.0
import QtQuick.Window 2.0
import QtQuick.Controls 1.2
import io.thp.pyotherside 1.5

//ApplicationWindow {  // Doesn't work
Window {  // Works
    PyGLArea {
        id: glArea
        anchors.fill: parent
    }

    Python {
        id: py
        Component.onCompleted: {
            addImportPath(Qt.resolvedUrl('.'));
            importModule('renderer', function () {
                call('renderer.Renderer', [], function (renderer) {
                    glArea.renderer = renderer;
                });
            });
        }
    }
}
```

renderer.py:
```python
from OpenGL.GL import *

class Renderer(object):
    def init(self):
        pass

    def reshape(self, x, y, width, height):
        glViewport(x, y, width, height)

    def render(self):
        glClearColor(1, 0, 0, 1)
        glClear(GL_COLOR_BUFFER_BIT)
```

When using Window from QtQuick.Window, I get a red window:
![window](https://cloud.githubusercontent.com/assets/1008108/8236263/18a11f2a-159c-11e5-899e-a1c769203442.png)

When using ApplicationWindow from QtQuick.Controls, I get a grey window (same result as not having the PyGLArea):
![application_window](https://cloud.githubusercontent.com/assets/1008108/8236262/189fa10e-159c-11e5-9987-8a07ac4dadf1.png)

I'm still not sure if this is a bug, or a limitation of ApplicationWindow.

**Comment by thp** [comment]
Thanks for the detailed example code, with this I should be able to reproduce it and analyze what's wrong. Not sure yet when I get around to do it, but it's easier to get started with this example code :)

**Comment by Moguri** [comment]
I have stumbled across a strange work-around: if you add a color property (with any value) to the ApplicationWindow, then the PyGLArea seems to work as expected. I'm wondering if assigning a color value is initializing OpenGL or some other state? Here's some example code:

```qml
import QtQuick 2.0
import QtQuick.Window 2.0
import QtQuick.Controls 1.2
import io.thp.pyotherside 1.5

ApplicationWindow {
    color: "black"
    PyGLArea {
        id: glArea
        anchors.fill: parent
    }

    Python {
        id: py

        Component.onCompleted: {
            addImportPath(Qt.resolvedUrl('.'));
            importModule('renderer', function () {
                call('renderer.Renderer', [], function (renderer) {
                    glArea.renderer = renderer;
                });
            });
        }
    }
}
```

And now I get the red PyGLArea (using the same renderer.py):

![application_window_w_color](https://cloud.githubusercontent.com/assets/1008108/8295379/fb462366-18f8-11e5-83d0-6dbb15a25008.png)

**Comment by thp** [comment]
Yes probably; closing as fixed with the workaround.
