### ISSUE TITLE
How to use other module like bs4,PIL,etc..

### ISSUE THREAD

**Issue by 0312birdzhang** [thp/pyotherside#48]
I see image_loader.py in youer examples, and found you use this code:
```
from PIL import Image
from PIL import ImageDraw
```

I want to use bs4 and PIL module in my sailfish app,i don't know how to use them.
Please help me ,thanks

**Comment by thp** [comment]
These libraries are not shipped in Sailfish OS. You might be able to ship them as private Python modules with your app or - during development - package PIL (or better Pillow) and install it on the device manually.
