### ISSUE TITLE
call_sync fails when used with parameters

### ISSUE THREAD

**Issue by basak** [thp/pyotherside#49]
I reduced this to the following test case:

```
import QtQuick 2.0
import io.thp.pyotherside 1.4

Rectangle {
    Python {
        Component.onCompleted: {
            addImportPath(Qt.resolvedUrl('.'));
            importModule('os', function () {
            call_sync('os.chdir', ['/']);
            });
        }
    }
}
```

This produces the error `Unhandled PyOtherSide error: Not a parameter list in call to os.chdir:`.

If I use `call` instead of `call_sync`, then it appears to work (including the callback if I'm calling a function that returns something useful. I believe `call` also works correctly when used without any parameters.

I'm using version 1.4.0, on Ubuntu Vivid (the distro packaged version 1.4.0-1).

**Comment by thp** [comment]
Is this still an issue with the version from Git?

**Comment by dawndiy** [comment]
@thp 
I met the same problem.
I build and install pyotherside using the newest version form Git. Then try to run the test, and the result is "Totals: 10 passed, 0 failed, 0 skipped, 0 blacklisted".
But when I run the code in test_callparam, I get the result below:
```
$ qmlscene test_callparam.qml 
Got library name:  "/usr/lib/x86_64-linux-gnu/qt5/qml/io/thp/pyotherside/libpyothersideplugin.so"
qml: Received error: Not a parameter list in call to print: 123
qml: Received error: Not a parameter list in call to print: 
```

**Comment by YtvwlD** [comment]
This is still an issue with the current `master`.

```
Unhandled PyOtherSide error: Not a parameter list in call to os.chdir:
```

**Comment by otsaloma** [comment]
@thp Any chance you could make a new release on account of this? It's currently broken in Sailfish OS 2.1.0.9, which for now is still in early access stage. It might be easier to get Sailfish OS / Mer to upgrade PyOtherSide if there was an actual release.

https://together.jolla.com/question/156736/

**Comment by M4rtinK** [comment]
Yeah, a patch-level release (1.5.1) should be enough for this - there are anyway only fixes on master since 1.5 has been released.

**Comment by thp** [comment]
I'll try to get around to do it this weekend. If not, please ping me on Monday.

**Comment by otsaloma** [comment]
Ping!

**Comment by M4rtinK** [comment]
Ping! :)

**Comment by YtvwlD** [comment]
Ping. :-)

**Comment by M4rtinK** [comment]
Ping.

**Comment by thp** [comment]
Finally done -- version 1.5.1 is now available from http://thp.io/2011/pyotherside/ and also tagged in Git.

**Comment by M4rtinK** [comment]
Nice, thanks a lot! :) I'll update the [Mer merge request](https://git.merproject.org/mer-core/pyotherside/merge_requests/2) & will add updating of PyOtherSide as a topic for the next Sailfish OS community meeting. :)

**Comment by M4rtinK** [comment]
Merge request has been updated & I've added "updating PyOtherSide" as a topic for the next [Sailfish OS community meeting](https://together.jolla.com/question/54157/sailfishos-open-source-collaboration-meeting-planning/). :)
