### ISSUE TITLE
Cannot build on Windows

### ISSUE THREAD

**Issue by IronManMark20** [thp/pyotherside#57]
~~I am attempting to build with Python 3.3, and Qt 5.5.1. I have followed the official instructions up to installing the project. It fails because in qpyhon_priv.cpp, on line 579, the PyObject_CallMethod fail, as it says it cannot transform from char[17] to char*~~

~~Sorry, I am not familiar with the Python C api, but it seems something is wrong here. It seems to expect 
` PyObject* PyObject_CallMethod(PyObject *o, char *method, char *format, ...)` as the signiture, but you seem to be calling with char arrays...~~

Got it building on Python 3.4 and Qt 5.5.1, however, now I am getting:

    QML module does not contain information about components contained in plugins.
    
    Module path: C:/Qt/Qt5.5.1/5.5/msvc2010/qml/io/thp/pyotherside
    See "Using QML Modules with Plugins" in the documentation.
    
    Automatic type dump of QML module failed.
    Errors:
    "C:\Qt\Qt5.5.1\5.5\msvc2010\bin\qmlplugindump.exe" returned exit code 3.
    Arguments: -nonrelocatable io.thp.pyotherside 1.4 C:/Qt/Qt5.5.1/5.5/msvc2010/qml
    QMutex: destroying locked mutex
     
whenever I try to use it. I am going to look to see if there are any easy fixes to this.

**Comment by IronManMark20** [comment]
@thp it seems that one needs to generate the qmltypes description of the module, which is not being generated. Could you provide that file?

**Comment by thp** [comment]
Yeah, I guess we have to create that file as written here: http://doc.qt.io/qt-5/qtqml-modules-qmldir.html#writing-a-qmltypes-file

I haven't written such a file yet, contributions welcome. Otherwise I can probably take a look at it at some point in the future (not sure when I'll find the time at the moment, though).

**Comment by IronManMark20** [comment]
@thp I might be able to build on my Linux partition, the files should be the same. I'll see what I can do.

Normally one would use the qmlplugindump, but that seems broken on Windows.

**Comment by IronManMark20** [comment]
@thp So it still isn't picking up anything. Have you tried on Windows recently? Thanks for any assistance!

**Comment by IronManMark20** [comment]
Closing as it will be closed in #58
