### ISSUE TITLE
Is it possible to cancel execution of some function?

### ISSUE THREAD

**Issue by uglide** [thp/pyotherside#59]
In some cases (plugins, long running jobs, etc) qml/c++ code should be able to cancel execution of python code. Is it possible to implement this feature in pyotherside?

If it possible, please point me to the right direction and I will implement it by myself. Thanks!

**Comment by zyga** [comment]
If you take pyotherside out of the problem how would you do it in pure python? You can try to cancel threads or raise exceptions in generators but it really depends on the problem you are trying to solve. Most of the time you would run an event loop inside python and explicitly cancel this loop but this requires careful non-blocking code.

**Comment by uglide** [comment]
@zyga  I'm trying to add possability in UI to stop some operation performed by python. If I add eventloop in python code and cancel execution - it doesn't work, so obviously this work should be perfomed on c++ side (probably in qpython class)

**Comment by M4rtinK** [comment]
Well, your call from QML code can just start the work on the Python side in
a thread that periodically reports progress by sending a progress signal
back to QML. Also while sending the signal the thread can check a Python
side variable, say named "shutdown_now", which if True tells the thread to
quit.

Then if you want to stop the operation performed by the Python thread, just
make a call from QML that sets the "shutdown_now" variable to True.

That should should cover the use case you have described.

2016-01-19 10:16 GMT+01:00 Igor Malinovskiy <notifications@github.com>:

**Comment by thp** [comment]
Yeah, this is mostly a "do it yourself" thing, I don't think we can have a generic solution. Especially since depending on what you do you might need to set socket timeouts, retries, etc..

Can we close this?
