### ISSUE TITLE
Compile error with python 3.5.2 from pyenv macOS Sierra

### ISSUE THREAD

**Issue by dagheyman** [thp/pyotherside#73]
I try to build pyotherside with python 3.5.2 from pyenv on macOS Sierra.
`PYENV_ROOT` is set to /usr/local/var/pyenv
make fails with:
`ld: -stack_size option can only be used when linking a main executable`

Any idea what the issue might be?

**Comment by thp** [comment]
Which Qt version are you using for compiling?

**Comment by dagheyman** [comment]
5.7.0

**Comment by thp** [comment]
I have tried to reproduce this issue on, but it built without problems:

macOS High Sierra 10.13.4
Qt 5.11.0 via Homebrew
Python 3.6.5 via Homebrew

Can you check if you can reproduce it with these settings? It could be that pyenv adds some incompatible compiler flags to the build, in that case, maybe forward this issue to the pyenv maintainers?
