### ISSUE TITLE
Pyotherside in Ubuntu SDK

### ISSUE THREAD

**Issue by SvenBo90** [thp/pyotherside#76]
Dear all,

I want to use pyotherside for my new Ubuntu Touch App. Unfortunately, I cannot make it run. I have a freshly installed Ubuntu 16.04 Desktop with Ubuntu SDK. When I try to apt-get pyotherside, I get 

pyotherside is already the newest version (1.4.0-2).

Which tells me, it should be properly installed on my system.

However, if I write a simple QML App within the Ubuntu SDK and run it I get

module "io.thp.pyotherside" is not installed

What am I missing?

Sven

**Comment by zyga** [comment]
The Ubuntu SDK doens't contain pyotherside. You need to bundle it yourself. The "checkbox-converged" project uses it in the SDK. Have a look at https://git.launchpad.net/checkbox-converged/tree/build-me and ask in the `#checkbox` channel on freenode for details.
