### ISSUE TITLE
Can't use Eve library with pyotherside

### ISSUE THREAD

**Issue by egfconnor** [thp/pyotherside#77]
I'm trying to setup an HTTP API in a QML project and when I run the simple quick start python code of:

```
from eve import Eve
app = Eve()
app.run()
```

it works using just Python but when I invoke this .py file with Pyotherside I get the following message:

> 
> "PyOtherSide error: Traceback (most recent call last):\n\n  File \"qrc://EveAPI.py\", line 6, in start\n    app = Eve()\n\n  File \"/home/connor/.local/lib/python3.5/site-packages/eve/flaskapp.py\", line 138, in __init__\n    self.load_config()\n\n  File \"/home/connor/.local/lib/python3.5/site-packages/eve/flaskapp.py\", line 230, in load_config\n    abspath = os.path.abspath(os.path.dirname(sys.argv[0]))\n\nAttributeError: module 'sys' has no attribute 'argv'\n"
> qml: python error: Return value of PyObject call is NULL: Traceback (most recent call last):
> 
>   File "qrc://EveAPI.py", line 6, in start
>     app = Eve()
> 
>   File "/home/connor/.local/lib/python3.5/site-packages/eve/flaskapp.py", line 138, in __init__
>     self.load_config()
> 
>   File "/home/connor/.local/lib/python3.5/site-packages/eve/flaskapp.py", line 230, in load_config
>     abspath = os.path.abspath(os.path.dirname(sys.argv[0]))
> 
> AttributeError: module 'sys' has no attribute 'argv'
>

**Comment by egfconnor** [comment]
I fixed it by adding my own

`sys.argv = ['']`

before the creation of Eve().

**Comment by egfconnor** [comment]
I seem to have found what may be the root issue here. If I do multiple addImportPath statements before my importModule in QML, it will throw weird errors such as this in the Python script. If I only have one addImportPath it behaves as expected.

**Comment by egfconnor** [comment]
File \"/usr/lib/python3.5/os.py\", line 112, in <module>\n    sys.modules['os.path'] = path\n\nAttributeError: module 'sys' has no attribute 'modules'\n"

This is the error I get anytime I do addImportPath twice. My goal is to be able to reference other Python modules from my Python script.

**Comment by egfconnor** [comment]
Alright I'm able to do multiple addImportPath with absolute paths like: `addImportPath('/home/connor/Repos/Test/source/src/Python/domain')`

but not like
`addImportPath(Qt.resolvedUrl('qrc:/Python/domain'))`

**Comment by thp** [comment]
Do you have a Short, Self Contained, Correct (Compilable), Example (http://sscce.org) for demonstrating the issue?

**Comment by egfconnor** [comment]
@thp I will put together an example as soon as I can.

**Comment by egfconnor** [comment]
Here is an example that shows my root import issues:

https://drive.google.com/file/d/0B5CPtCs60_W-U3ZEX2E2T3NpU3c/view?usp=sharing

Am I supposed to always have my Python and QML files in the same directory?

**Comment by egfconnor** [comment]
I'm still investigating how the importing works. If I take your example project and change it from qrc_example.py to anything else...say test.py, update the .qrc file and .qml file to reference it...it won't work. It will say it had success importing the module but the 'Hello from module!' won't print nor can I call any specific functions.

**Comment by thp** [comment]
No, there is no such requirement, but you might need to tweak the Python import path.

**Comment by egfconnor** [comment]
So I finally remembered this issue and I've noticed it with other libraries too and it boils down to the embedded Python doesn't get the sys.argv attribute set by default. 

Before importing the offending libraries, which for me have been Eve or systemd-python, you can simply set: sys.argv  = [''] and it will cause things to work.

I wonder if for wider Python library use in Pyotherside if we should call PySys_SetArgv with an empty array right after you call Py_InitializeEx(0)? This would be preferable to currently where it will just break when importing a certain library.

I have tested this in the Pyotherside library and it works:

Py_InitializeEx(0);

wchar_t** wargv = (wchar_t**) malloc(0 * sizeof(wchar_t*));
or
wchar_t* wargv[0];

PySys_SetArgv(0, wargv);


> void Py_Initialize()
> Initialize the Python interpreter. In an application embedding Python, this should be called before using any other Python/C API functions; with the exception of Py_SetProgramName(), Py_SetPythonHome() and Py_SetPath(). This initializes the table of loaded modules (sys.modules), and creates the fundamental modules builtins, __main__ and sys. It also initializes the module search path (sys.path). It does not set sys.argv; use PySys_SetArgvEx() for that. This is a no-op when called for a second time (without calling Py_FinalizeEx() first). There is no return value; it is a fatal error if the initialization fails.
