### ISSUE TITLE
Unknown component

### ISSUE THREAD

**Issue by hit1001** [thp/pyotherside#80]
When using 
Python {
id: py
..
..

}

It shows unknown component and qml file does not build. Making sure i already am importing "import io.thp.pyotherside 1.5" in a .qml file.

**Comment by thp** [comment]
How did you install PyOtherSide?

**Comment by kuba-orlik** [comment]
I'm also experiencing this issue. I've installed pyotherside via the `python-pyotherside` package with `pacman`

**Comment by kuba-orlik** [comment]
Also, tried with `qmake && make && sudo make install` route, with the same effect - "Unknown component"
