### ISSUE TITLE
QML Plugin not loading on Windows

### ISSUE THREAD

**Issue by JustinSteventon** [thp/pyotherside#90]
I'm getting the following:
QQmlApplicationEngine failed to load component
qrc:/main.qml:4 plugin cannot be loaded for module "io.thp.pyotherside": Cannot load library C:\Qt\5.10.0\msvc2015\qml\io\thp\pyotherside\pyothersideplugin1.dll: The specified module could not be found.

The DLL exists in that location (alongside Python37.dll which it links to).

I followed the steps in the tutorial for building, including building Python and deploying the plugin. Everything was successful with a couple of exceptions:
1. In qpython_priv.cpp I had to add a "constexpr" before "int argc = 1;":
    constexpr int argc = 1;
    wchar_t *argv[argc];
2. In the Building For Windows section of the developers guide, step (6) should be "Hit Deploy to install PyOtherSide in your local Qt folder"

Looks like a very interesting tool. If it could be a little easier to install that would be great.

**Comment by JustinSteventon** [comment]
Turns out the problem was that I had to copy Python*.dll to my exe folder. Also my build using MSVC 2015 tools was somehow broken. Using the prebuilt libraries works though.

**Comment by Elwycliffs** [comment]
Been trying to build pyotherside on Windows with no success. Please advise.
What Qt version should I use?
What VS C++ (Express) Compiler version should I use?
MSVC 2015?? 64bit or 32bit??

or better, is it possible to share your version of the build?

**Comment by thp** [comment]
Please always try with the latest MSVC version (2017 as of this writing), the Community Editions are free for open source projects.

**Comment by BlueKenny** [comment]
Is there an Windows build i can use ?

(We have 2 Windows PCs at work :/...)
