### ISSUE TITLE
Crash when trying plotorama example

### ISSUE THREAD

**Issue by Kenichiro-Yoshimi** [thp/pyotherside#91]
When trying to run the plotorama example with qmlscene, a crash happens without any error message. If I skip the process of saving a figure, the crash is not caused, that is in plotorama.py,
`#plt.savefig(buf, format='png')`

Any help would be highly appreciated.

Windows 10
Python 3.5.2 |Anaconda 4.2.0 (64-bit) [MSC v.1900 64 bit (AMD64)]
Qt: 5.10.0

**Comment by thp** [comment]
Do you have matplotlib for the Python version you are using installed?

**Comment by Kenichiro-Yoshimi** [comment]
I updated the version of matplotlib to 2.2.2, but it was still the same situation. So, I change to ActivePython 3.6 from Anaconda and it works well. Perhaps I am missing something very obvious with the Anaconda package, but I close this.

Thanks
