### ISSUE TITLE
 #Error "Module 'io.thp.pyotherside' is not installed

### ISSUE THREAD

**Issue by Elwycliffs** [thp/pyotherside#94]
I keep getting this error when compiling and running a project with the import in QtCreator. The import statement is also underlined in red within the qml editor indicating an import error.

I followed the build steps as per the documentation for Linux systems i.e
$ qmake PYTHON_CONFIG=/usr/bin/python3.6-config
$ sudo make && sudo make install
$ sudo qmlplugindump io.thp.pyotherside 1.0 /usr/lib/qt/qml/io/thp/pyotherside/ > src/pyotherside.qmltypes

@thp Could you take me through the build process for Linux systems.
My System: Arch Linux
Qt: 5.10
Python: 3.6.5
QtCreator 4.6

**Comment by thp** [comment]
What are you trying to run? Do you have different Qt versions installed? Does `sudo make install` install the QML plugin in the right directory?

**Comment by toby20130333** [comment]
I meet the same error :
qrc:/main.qml:3 module "io.thp.pyotherside" plugin "pyothersideplugin" not found
my qml code:
import QtQuick 2.10
import QtQuick.Window 2.10
import io.thp.pyotherside 1.5

My System: win 10
Qt: 5.12
Python: 3.6.5
I make install the io pyotherside plugin in qml plugin path

**Comment by toby20130333** [comment]
I find a solution：
Please put the python.dll in execute path
