### ISSUE TITLE
Help Building on FreeBSD 11.2-RELEASE

### ISSUE THREAD

**Issue by BlueKenny** [thp/pyotherside#96]
Hello,
I'm trying to build pyotherside on my FreeBSD PC

I'm using Python3.6 and followed the doc.

i used "qmake PYTHON_CONFIG=/usr/local/bin/python3.6-config" (i checked this path)
By running "make" i get the Error "Python.h file not found" at qpython_priv.h:22:10

the python includes are in "/usr/local/include/python3.6m/", how can i pass this path to "make" ?

**Comment by thp** [comment]
What's the output of `/usr/local/bin/python3.6-config --includes` on your machine?

At `qmake` time, you could set `QMAKE_CFLAGS` and `QMAKE_CXXFLAGS` to override the include dirs? https://stackoverflow.com/a/17578151/1047040

**Comment by thp** [comment]
@BlueKenny Any update on this?

**Comment by BlueKenny** [comment]
Hey, sorry don't know if it the build work but its in the ports know :) 
Thanks, in few days i will try manual building to know it the new version works too

**Comment by thp** [comment]
Neat: https://www.freshports.org/devel/pyotherside-qt5/
Closing as "fixed".
Feel free to open another issue if you hit into any packaging issues on FreeBSD.
