### ISSUE TITLE
keyword arguments

### ISSUE THREAD

**Issue by aitzol76** [thp/pyotherside#97]
Hi,
I'm trying to make a call from QML using keyword arguments in this way:
`

           id: python
             Component.onCompleted: {

                addImportPath(Qt.resolvedUrl('./'));
                importModule('app', function() {
                    console.log('app module imported');
                    call('app.main.myfunction', [{'key1':'value', 'key2':'value'}], function(res){
                        console.log(res)
                    });
                    ..........
                    ........
                    ....
`
but 'myfunction' in app.py doesn't receive anything:

`

      def myfunction(*args, **kwargs):
          print(kwargs)
`
I also trying with ["**"+{'key1':'value', 'key2':'value'}] but doesn't work. Is there a way to pass **kwargs arguments?

**Comment by thp** [comment]
It's not possible to supply keyword arguments, but you can pass a JavaScript object as normal parameter and it will arrive as Python dict:
```
    call('app.main.myfunction', [{'key1':'value', 'key2':'value'}], ...);
```

And in Python:
```
    def myfunction(arg):
        print(arg)
```

And of course this dict you can then pass to another function that uses kwargs.

**Comment by thp** [comment]
See previous comment for a workaround.
